module.exports = {
    INITIALIZING: 'INITIALIZING',
    INITIALIZED: 'INITIALIZED',
    LIGHT_ON: 'LIGHT_ON',
    LIGHT_OFF: 'LIGHT_OFF',
    LIGHT_UPDATING: 'LIGHT_UPDATING',
    LIGHT_TOGGLE: 'LIGHT_TOGGLE'
};
